server:
  port: ${PORT}
  protocol: ${PROTOCOL}
  domain: ${DOMAIN}
  external-port: ${EXTERNAL_PORT}

spring:
  application:
    name: account-server
  config:
    import: optional:file:.env[.properties]
  r2dbc:
    account:
      url: ${ACCOUNT_DATABASE_URL}
      username: ${ACCOUNT_DATABASE_USERNAME}
      password: ${ACCOUNT_DATABASE_PASSWORD}
    game:
      url: ${GAME_DATABASE_URL}
      username: ${GAME_DATABASE_USERNAME}
      password: ${GAME_DATABASE_PASSWORD}
  sql:
    init:
      mode: never

jwt:
  access-private-key: ${JWT_PRIVATE_KEY}
  access-public-key: ${JWT_PUBLIC_KEY}